from __future__ import annotations
from dataclasses import dataclass, field, KW_ONLY
from contextlib import contextmanager

@dataclass
class ChatMessage:


@dataclass
class Log[T](list):
  """A Sequence of items"""

@dataclass
class Content[T]:
  """Models content supported by an LLM"""
  buffer: T

@dataclass
class TextContent(Content[str]): ...
@dataclass
class ImageContent(Content[bytes]): ...

@dataclass
class UsageMetrics:
  """Models Token Usage Metrics"""
  input_tokens: int
  output_tokens: int

@dataclass
class LLMOutput:
  """Models the output generated by an LLM contextualized to the provider"""
  ok: str
  content: TextContent | ImageContent
  usage: UsageMetrics

  def __bool__(self) -> bool:
    return self.ok

@dataclass
class LLMProvider:
  """Models an LLM backend provider"""

  def get_model(self, model: str) -> LLM:
    """Get the provided Model"""
    raise NotImplementedError

@dataclass
class LLM:
  """Models an LLM"""
  name: str
  """The Human friendly name"""
  id: str
  """The Provider's Model ID Slug"""
  kind: ModelKind
  """The classification of Model"""
  capabilities: ModelCapabilities
  """The capabilities provided by the model"""

  @contextmanager
  def tune(self, **opts) -> LLM:
    """Returns a view on the LLM w/ the tuning parameters applied"""
    raise NotImplementedError
  
  def prompt(self, *args, **kwds) -> LLMOutput:
    """The Model Output"""
    raise NotImplementedError


@dataclass
class Chat:
  """A Baseline Chat interface"""

  def __call__(self, log: Log[ChatMessage]):

    ### Assemble the Chat Log
    chat_log = [
      # ... TODO
    ]

    ### Prompt the LLM
    with provider.get_model(model).tune(
      **model_opts
    ) as tuned_llm: # Adjust the model runtime
      reply: LLMOutput = tuned_llm.prompt(
        *chat_log, # The sequence of messages to prompt the LLM with
      )
    
    ### Process the response
    if not reply: raise NotImplementedError('Handled Bad Response')

    assert reply.ok == True

    response = ...

    return response

@dataclass
class Conversation:
  """Track's a 